title: ∆ U = Q - W
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://github.com/RNBrandt/RNBrandt.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: RNBrandt
   #twitter: brianmaierjr
   facebook: Reuben.Brandt
   email: ReubenNBrandt@gmail.com

google_analytics: "UA-58263416-1"
